language: python
python:
  - "3.7.4"

install:
  - sudo apt-get update

  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment

  - python setup.py install
#  - conda build your-conda-recipe
#  - conda install your-package --use-local

script:
  - pytest

after_success:
  - conda install conda-build
  - conda install anaconda-client
  - export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN
  - echo "lssss"
  - ls
  - conda build .
  - ls build
  - ls dist
  - ls $CONDA_BLD_PATH
  - conda convert --platform all $CONDA_BLD_PATH/linux-64/$PKG_NAME-$VERSION.tar.bz2 --output-dir $CONDA_BLD_PATH/

  - anaconda upload $CONDA_BLD_PATH/**/test_release-*.tar.bz2

#  - test $TRAVIS_BRANCH = "master" && conda install conda-build && conda install anaconda-client && bash conda_upload.sh